### ISSUE TITLE
noResultsMessage

### ISSUE THREAD

**Issue by ebda3is** [ng-pros/np-autocomplete#3]
Hi,
when I fill my Model manually and click in the textbox, The "noResultsMessage" message is appear although the Model is not empty.
![issue](https://cloud.githubusercontent.com/assets/1777235/11333270/22a3ac1c-91d5-11e5-97eb-dd422c36b96d.jpg)

**Comment by raeef-refai** [comment]
would you share us the code you use please?

**Comment by ebda3is** [comment]
<div class="form-group" np-autocomplete="npOptions">
                                <input type="text" class="form-control" id="UserName" ng-model="SelectedUser.Name"/>
                                <span class="glyphicon glyphicon-refresh glyphicon-refresh-animate form-control-feedback" ng-show="loading"></span>
                                <span class="glyphicon glyphicon-remove" ng-click="ShowAllUsers(false)"></span>
                            </div>

Thanks

**Comment by ebda3is** [comment]
<div class="form-group" np-autocomplete="npOptions">
    <input type="text" class="form-control" id="UserName" ng-model="SelectedUser.Name"/>
    <span class="glyphicon glyphicon-refresh glyphicon-refresh-animate form-control-feedback" ng-show="loading"></span>
    <span class="glyphicon glyphicon-remove" ng-click="ShowAllUsers(false)"></span>
</div>

**Comment by ebda3is** [comment]
![image](https://cloud.githubusercontent.com/assets/1777235/11916377/ee67797a-a6dc-11e5-8779-642c06828fbb.png)

**Comment by raeef-refai** [comment]
Well.. you should move `ng-model` from the `input` element to the directive itself which is the parent of the input element in your case
