### ISSUE TITLE
My api route format is not working with np-autocomplete

### ISSUE THREAD

**Issue by tirumalavasu** [ng-pros/np-autocomplete#4]
I have api in params format
i.e., http://localhost:9000/api/villages/searchroot/ki

But this is checking for query format
i.e, http://localhost:9000/api/villages?searchroot=ki

How to get it work.

**Comment by raeef-refai** [comment]
mmm, you can't do that now, but I'll make that possible ASAP.

**Comment by raeef-refai** [comment]
I've added a new option `queryMode` to make that possible.
refer to [README.md](https://github.com/ng-pros/np-autocomplete/blob/master/README.md) to know more about it.

**Comment by tirumalavasu** [comment]
that's awesome. thanks a lot.

**Comment by raeef-refai** [comment]
support this plugin by staring and forking it.

**Comment by tirumalavasu** [comment]
Sorry for late reply, I am getting error if i includes queryMode in options...

![npaa](https://cloud.githubusercontent.com/assets/3540345/12167073/07128452-b550-11e5-9b14-c0ce9e412144.png)

this is my html:

```
<div class="form-group" np-autocomplete="npAutocompleteOptions" ng-model="repoID">
                <input type="text" class="form-control" />
 </div>
```

this is my controller js:

```
$scope.npAutocompleteOptions = {
          url: 'api/villages/searchonlyvillages/',
          limit: 5,
          delay: 500,
          params: {},
          dataHolder: 'villages',
          nameAttr: 'village.Village',
          minlength: 1,
          valueAttr: 'village._id',
          queryMode: false,
          limitParam: 'limit',
          highlightExactSearch: true
        };
```

**Comment by raeef-refai** [comment]
your url should be as the following:
`api/villages/searchonlyvillages/:searchParam`

**Comment by alpaaps** [comment]
Hi, 
An idea of enhancement would be to add ":limitParam" to the param mode, if possible. 

Cheers and thanks for this plugin

**Comment by raeef-refai** [comment]
will do that ASAP.
