### ISSUE TITLE
error when used in ng-repeat

### ISSUE THREAD

**Issue by adrianriepl** [ng-pros/np-autocomplete#7]
When I use the directive in a ng-repeat I get an error:

_$compile:multilink
Linking Element Multiple Times
This element has already been linked._

**Comment by psmul** [comment]
Hello,
Any info about bug possible fix? 

I have the same issue while just reloading part of my component (clicking on element to make if visible and hidden which forces re-compiling).

**Comment by raeef-refai** [comment]
sorry guys, I've been busy.
I'll check it ASAP, if any of you have the fix, just send me a PR.

**Comment by raeef-refai** [comment]
@DarkNami has resolved this issue and I published a new beta version 2.2.0-beta.0

**Comment by mitomm** [comment]
Has this issue bin resolved in 2.2.0? 
Facing the same issue right now with 2.1.1.

Why is there still a beta tag on 2.2.0. Is it save to use? Any breaking changes as of 2.1.1.

Thanks for help.
